version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
    - unconvert
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports
